start.all:
	docker-compose --profile full-expenses-bot up -d --build

start.connector:
	docker-compose --profile just-connector up -d --build

start.bot:
	docker-compose --profile just-expenses-bot up -d --build
